"""Remove tables for Signature and SignatureSet models

Revision ID: 8e4286c25e33
Revises: 68acf3fff58d
Create Date: 2017-11-05 11:24:26.151562

"""
from alembic import op
import sqlalchemy as sa
import gambit.db.sqla


# revision identifiers, used by Alembic.
revision = '8e4286c25e33'
down_revision = '68acf3fff58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signatures')
    op.drop_table('signature_sets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_sets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('prefix', sa.VARCHAR(), nullable=False),
    sa.Column('k', sa.INTEGER(), nullable=False),
    sa.Column('parameters', sa.VARCHAR(), nullable=False),
    sa.Column('extra', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signatures',
    sa.Column('set_id', sa.INTEGER(), nullable=False),
    sa.Column('genome_id', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.Column('dtype_str', sa.VARCHAR(length=2), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['genomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['signature_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'genome_id')
    )
    # ### end Alembic commands ###
