"""v2.0.1

Add "report" column to taxa

Revision ID: 68acf3fff58d
Revises: 955d795123c3
Create Date: 2017-08-31 13:04:08.811277

"""
from alembic import op
import sqlalchemy as sa
import midas.db.sqla


# revision identifiers, used by Alembic.
revision = '68acf3fff58d'
down_revision = '955d795123c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxa', schema=None) as batch_op:
        batch_op.drop_column('report')

    # ### end Alembic commands ###
