"""Remove unneeded columns

Revision ID: d961d0698083
Revises: 4815cccfb01b
Create Date: 2020-10-27 11:37:59.455985

"""
from alembic import op
import sqlalchemy as sa
import midas.db.sqla


# revision identifiers, used by Alembic.
revision = 'd961d0698083'
down_revision = '4815cccfb01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.drop_index('ix_genomes_ncbi_taxid')
        batch_op.drop_column('entrez_summary')
        batch_op.drop_column('ncbi_taxid')
        batch_op.drop_column('is_assembled')

    with op.batch_alter_table('reference_genome_sets', schema=None) as batch_op:
        batch_op.drop_column('signatureset_version')
        batch_op.drop_column('signatureset_key')

    with op.batch_alter_table('taxa', schema=None) as batch_op:
        batch_op.drop_column('entrez_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrez_data', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('reference_genome_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signatureset_key', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('signatureset_version', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assembled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ncbi_taxid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('entrez_summary', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_genomes_ncbi_taxid', ['ncbi_taxid'], unique=False)

    # ### end Alembic commands ###
