package:
  name: midas
  version: '2.0.0'

source:
  path: ../ 

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5
    - setuptools >=27
    - cython >=0.24
    - numpy >=1.11

  run:
    - python >=3.5
    - numpy >=1.11
    - biopython >=1.68
    - sqlalchemy >=1.0
    - alembic >=0.8

test:
  source_files:
    - tests/*
  requires:
    - pytest
  commands:
    - py.test tests/

