name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      TESTDB_DIR: tests/data/testdb_210126

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache test database
      id: cache-test-database
      uses: actions/cache@v2
      with:
        path: ${{ env.TESTDB_DIR }}
        # Increment the number on the end every time the test data changes
        key: testdb-data-2

    - name: Download test database
      if: steps.cache-test-database.outputs.cache-hit != 'true'
      env:
        BASE_URL: https://storage.googleapis.com/hesslab-gambit-public/databases/testdb_210126
      run: |
        mkdir $TESTDB_DIR/query-seqs
        wget -O $TESTDB_DIR/testdb_210126-signatures.h5 $BASE_URL/testdb_210126-signatures-210707.h5
        wget -O - $BASE_URL/testdb_210126_query_seqs.tar.gz | tar -xz -C $TESTDB_DIR/query-seqs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools Cython numpy pytest

    - name: Build package
      run: |
        pip install .

    - name: Test with pytest
      env:
        PY_IGNORE_IMPORTMISMATCH: 1
      run: |
        pytest --midas-test-full-db
